# GitHub Actions workflow, which runs on push to a branch.
# See https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.5
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: build test integrationTest